version: '3.8'
services:
  app:
    container_name: nodejs-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=CyTechDDBB
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: mysql-database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CyTechDDBB
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
